---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - hwgroup.mydomain.io
  resources:
  - helloworldoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hwgroup.mydomain.io
  resources:
  - helloworldoperators/finalizers
  verbs:
  - update
- apiGroups:
  - hwgroup.mydomain.io
  resources:
  - helloworldoperators/status
  verbs:
  - get
  - patch
  - update
