apiVersion: hwgroup.mydomain.io/v1
kind: HelloWorldOperator
metadata:
  labels:
    app.kubernetes.io/name: hello-world-operator
    app.kubernetes.io/managed-by: kustomize
  name: helloworldoperator-sample
  namespace: hello-world-operator-system
spec:
  scrapeInterval: 20s
